#!/usr/bin/env python3
"""Structure check for this repo, plus generation of MODULE_MAP.md and .sop/function_index.json.

Vendored from an upstream module-structure checker and adapted for this repo's own module
conversion (the Python import-contract piece only; later upstream checker changes are not
included). Adapted, in order:

- Registered-modules-only (the repo is modularized one module at a time): a large legacy
  repo being modularized incrementally, so the upstream tool's exhaustive "every top-level folder must be
  registered or in non_module_dirs" scan does not apply here -- it would fail on day one against every
  pre-existing legacy folder (docker/, docs/, scripts/, src/, ...). This check now verifies only that each
  REGISTERED module's own path exists, and, once inside a registered module, that its sub-folders are
  themselves registered sub-modules (module-internal structure discipline still applies; only the repo-root
  legacy scan is relaxed). A later PR that finishes modularizing the repo can restore the exhaustive scan.
- A missing `project.architecture_word_budget` key is a loud, named FAIL ("NOT-CHECKED"), never a
  silent skip and never a KeyError crash.
- `_function_index` now also walks module-level `Assign`/`AnnAssign` targets (constants, e.g. `LIMITS`),
  not just `FunctionDef`/`ClassDef` -- the upstream walk silently missed every constant export. (The
  `__all__`-aware comparison lives in doc_check.card_findings via `_code_public`, imported below.)
- 5b (a new check, not an upstream one): a package-entry-point-bypass check. The upstream import-contract
  check only ever inspects an import's FIRST dotted component, which never matches this repo's absolute
  dotted-import style (`turbohaul.engine_launch`) -- so it could never actually catch a module reaching
  past another module's `__init__.py`. See the check's own comment, below, for the fix.
- 5c RELATIVE imports (a port of the upstream checker's fix, taking only this one piece
  of the upstream checker):
  a relative import (`from .x import y` / `from ..x import y`) was invisible to 5c/5b,
  which only ever compared an ABSOLUTE dotted `node.module` -- resolved via `importlib.util.resolve_name`
  against the importing file's own package before the same prefix/exact match, below.
- Word-count encoding: the ARCHITECTURE.md word count now opens the file
  with an explicit `encoding='utf-8'` -- Python's bare `open()` otherwise falls back to
  `locale.getpreferredencoding()`, which disagreed with a shell `wc -w` count on systems with
  different locales. The count is identical under both `LANG` unset and `LANG=C.UTF-8`.

Usage: tools/sop_check.py [--write] [REPO_ROOT]
  default  check only; exit 1 on any failure (a stale generated file is a failure)
  --write  regenerate MODULE_MAP.md and .sop/function_index.json first, then check
"""
import ast
import importlib.util
import json
import os
import sys
import tomllib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from doc_check import card_findings  # noqa: E402

CARD_SECTIONS = ['Purpose', 'Owns', 'Does Not Own', 'Public Interface', 'Depends On', 'Invariants',
                 'Test Locations', 'Known Gotchas']
CODE_EXT = ('.py', '.sh')


def load_registry(root):
    """Return the parsed modules.toml."""
    with open(os.path.join(root, 'modules.toml'), 'rb') as f:
        return tomllib.load(f)


def _module_map(reg):
    """Return the generated MODULE_MAP.md text (one line per module, registry order)."""
    lines = ['# MODULE MAP (generated by tools/sop_check.py --write; never hand-edit)', '']
    for name, m in reg['modules'].items():
        deps = ', '.join(m.get('depends_on', [])) or 'none'
        lines.append(f"- **{name}** `{m['path']}` - owns: {m['owns']} | depends on: {deps} | card: `{m['card']}`")
    return '\n'.join(lines) + '\n'


def _function_index(root, reg):
    """Return the function index (public functions/classes/constants of every code module), as a JSON string.

    Extended to module-level Assign/AnnAssign targets, not just FunctionDef/ClassDef -- this is
    a reuse-search index (a "search before you write" rule), so it deliberately stays broader than
    the registry's public list: any non-underscore top-level name is a reuse candidate, exported or not.
    """
    out = []
    for name, m in reg['modules'].items():
        base = os.path.join(root, m['path'])
        for fn in sorted(os.listdir(base)):
            if not fn.endswith('.py'):
                continue
            tree = ast.parse(open(os.path.join(base, fn)).read())
            for node in tree.body:
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) and not node.name.startswith('_'):
                    sig = ''
                    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                        sig = '(' + ', '.join(a.arg for a in node.args.args) + ')'
                    out.append({'module': name, 'name': node.name, 'signature': sig,
                                'doc': (ast.get_docstring(node) or '').split('\n')[0],
                                'file': f"{m['path']}/{fn}", 'line': node.lineno})
                elif isinstance(node, ast.Assign):
                    for t in node.targets:
                        if isinstance(t, ast.Name) and not t.id.startswith('_'):
                            out.append({'module': name, 'name': t.id, 'signature': '', 'doc': '',
                                        'file': f"{m['path']}/{fn}", 'line': node.lineno})
                elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and not node.target.id.startswith('_'):
                    out.append({'module': name, 'name': node.target.id, 'signature': '', 'doc': '',
                                'file': f"{m['path']}/{fn}", 'line': node.lineno})
    return json.dumps(out, indent=1) + '\n'


def dotted_import_name(root, module_path):
    """Derive module_path's Python dotted import name: walk up from the module's
    own folder while __init__.py exists, stopping at the first ancestor that doesn't -- that
    ancestor is the import root. Returns (dotted_name, None) on success, or (None, error) when
    derivation cannot be trusted:
      - the module's own folder isn't even a package (no __init__.py) -- the module system requires a
        registered module to be a package with an __init__.py entry point, so this is itself a
        real defect, not merely a derivation failure;
      - the ancestor chain has a GAP -- some directory between the module and the repo root is
        missing __init__.py, but a directory further up (closer to the repo root) HAS one. A
        gap makes "where the real import root is" genuinely ambiguous from folder structure
        alone: silently picking the nearer boundary could derive a dotted name that doesn't
        match how legacy code actually imports this module, which would make the import-contract
        check below silently find zero violations even where real ones exist -- worse than
        refusing to check. Design decision: loud FAIL, never a silent skip.
    """
    parts = module_path.split('/')
    if not os.path.isfile(os.path.join(root, module_path, '__init__.py')):
        return None, f'{module_path}: not a package (no __init__.py) -- cannot derive a dotted import name'
    has_init = [os.path.isfile(os.path.join(root, '/'.join(parts[:i]), '__init__.py'))
                for i in range(len(parts), 0, -1)]
    seen_false = False
    for v in has_init:
        if not v:
            seen_false = True
        elif seen_false:
            return None, (f'{module_path}: ancestor chain has a gap -- a directory missing __init__.py '
                          f'with another package ancestor above it -- cannot safely derive a dotted '
                          f'import name')
    top = 0
    for v in has_init:
        if not v:
            break
        top += 1
    return '.'.join(parts[len(parts) - top:]), None


_LEGACY_SCAN_SKIP_DIRS = {'.git', '__pycache__', '.pytest_cache', 'node_modules', '.sop'}


def _iter_repo_py_files(root):
    """Every .py file under root, skipping VCS/cache/build noise (the legacy scan --
    it must see files OUTSIDE every registered module too, since every real importer here is legacy)."""
    for dp, dn, files in os.walk(root):
        dn[:] = [d for d in dn if d not in _LEGACY_SCAN_SKIP_DIRS]
        for fn in files:
            if fn.endswith('.py'):
                yield os.path.join(dp, fn)


def check(root, write=False):
    """Run every structure check. Returns (failures, warnings) as lists of strings."""
    fails, warns = [], []
    reg = load_registry(root)
    proj, mods = reg['project'], reg['modules']
    registered = {m['path'] for m in mods.values()}
    # 1. registry -> folders: every REGISTERED module's path must exist. This repo is
    #    modularizing one fix at a time, so unregistered legacy folders at the repo root are expected and
    #    are NOT scanned for here (contrast the upstream, fully-modularized-repo tool, which flags every
    #    unregistered top-level folder).
    #
    #    A module whose registered path does not exist is a clean, named FAIL
    #    here -- and is then SKIPPED by every later per-module check (#2 onward), which otherwise crash trying
    #    to os.listdir()/open() a path that was never there (the upstream tool's own pre-existing gap; fixed
    #    here rather than merely documented, since this fault category must actually be
    #    caught, not crash).
    missing = set()
    for name, m in mods.items():
        if not os.path.isdir(os.path.join(root, m['path'])):
            fails.append(f'{name}: registered path {m["path"]} does not exist')
            missing.add(name)
    mods = {n: m for n, m in mods.items() if n not in missing}  # every check below sees only LIVE modules
    reg = {**reg, 'modules': mods}
    # 1a. folders -> registry, but ONLY inside an already-registered module: once code is in the module
    #     system, sub-folder registration discipline still applies (a sub-module needs its own registry entry).
    for p in sorted(registered):
        full = os.path.join(root, p)
        for d in sorted(os.listdir(full)) if os.path.isdir(full) else []:
            sub = f'{p}/{d}'
            if os.path.isdir(os.path.join(full, d)) and d not in ('references', '__pycache__') and sub not in registered:
                fails.append(f'unregistered sub-folder: {sub}')
    # 1b. nesting: a registered module inside another registered module's folder is a sub-module (any depth),
    #     so its depends_on must name its direct parent, the nearest registered ancestor folder
    by_path = {m['path']: n for n, m in mods.items()}
    for name, m in mods.items():
        parts = m['path'].split('/')
        for i in range(len(parts) - 1, 0, -1):
            parent = by_path.get('/'.join(parts[:i]))
            if parent:
                if parent not in m.get('depends_on', []):
                    fails.append(f'{name}: sub-module of {parent}, but depends_on does not name its parent')
                break
    # 2. every module card exists with every required section
    for name, m in mods.items():
        card = os.path.join(root, m['card'])
        if not os.path.isfile(card):
            fails.append(f'{name}: card missing: {m["card"]}')
            continue
        text = open(card).read()
        for s in CARD_SECTIONS:
            if f'\n## {s}\n' not in '\n' + text:
                fails.append(f'{name}: card section missing: ## {s}')
        for dep in m.get('depends_on', []):
            if dep not in mods:
                fails.append(f'{name}: depends_on unknown module {dep}')
    # 2b. module docs: README present, card matches registry and code, parent README names its sub-modules
    fails.extend(card_findings(root, reg))
    # 3. line caps on code (modules may be exempt only via line_cap_exempt, which needs an ADR)
    for name, m in mods.items():
        if m.get('line_cap_exempt'):
            continue
        for dp, _dn, files in os.walk(os.path.join(root, m['path'])):
            for fn in files:
                if fn.endswith(CODE_EXT):
                    n = sum(1 for _ in open(os.path.join(dp, fn)))
                    rel = os.path.relpath(os.path.join(dp, fn), root)
                    if n > proj['line_cap_hard']:
                        fails.append(f'{rel}: {n} lines > hard cap {proj["line_cap_hard"]}')
                    elif n > proj['line_cap_soft']:
                        warns.append(f'{rel}: {n} lines > soft cap {proj["line_cap_soft"]}')
    # 4. architecture doc word budget. A missing key is a loud, named FAIL, never a silent
    #    skip and never a KeyError crash.
    if 'architecture_word_budget' not in proj:
        fails.append('architecture_word_budget: NOT-CHECKED -- project.architecture_word_budget is missing '
                     'from modules.toml, so ARCHITECTURE.md\'s word count was not verified')
    else:
        # Explicit encoding='utf-8' -- Python's own open()
        # without one falls back to locale.getpreferredencoding(), which made this
        # exact call disagree with a shell `wc -w` on systems with different
        # locales. Decoding is pinned here so the count never
        # depends on the process locale again.
        words = len(open(os.path.join(root, 'ARCHITECTURE.md'), encoding='utf-8').read().split())
        if words > proj['architecture_word_budget']:
            fails.append(f'ARCHITECTURE.md: {words} words > budget {proj["architecture_word_budget"]}')
    # 5. import contract: code in a module may import only its own files (stdlib otherwise)
    local = {n: {fn[:-3] for fn in os.listdir(os.path.join(root, m['path'])) if fn.endswith('.py')} for n, m in mods.items()}
    for name, m in mods.items():
        for fn in local[name]:
            tree = ast.parse(open(os.path.join(root, m['path'], fn + '.py')).read())
            for node in ast.walk(tree):
                names = [a.name for a in node.names] if isinstance(node, ast.Import) else (
                    [node.module] if isinstance(node, ast.ImportFrom) and node.module else [])
                for imp in names:
                    for other, files in local.items():
                        if other != name and other not in m.get('depends_on', []) and imp.split('.')[0] in files:
                            fails.append(f'{m["path"]}/{fn}.py imports {imp} from module {other} (not in depends_on)')
    # 5b. import contract, package entry point: the upstream check above only ever inspects an
    #     import's FIRST dotted component (`imp.split('.')[0]`), which only catches a bare, non-package-style
    #     import (`import name`). Every real import in this repo is an absolute dotted path from the project
    #     root (`pkg.module.name`), where the file being reached into is the LAST component, not
    #     the first -- so #5 alone can never catch a real "reached past the entry point" violation here. A
    #     registered PACKAGE module (one with an __init__.py) may only be entered through it: reaching into one
    #     of its other files directly is wrong even from a module that legitimately depends_on it -- this is a
    #     stricter, independent rule from #5's "declared dependency" check.
    packages = {n for n, files in local.items() if '__init__' in files}
    for name, m in mods.items():
        for fn in local[name]:
            tree = ast.parse(open(os.path.join(root, m['path'], fn + '.py')).read())
            for node in ast.walk(tree):
                names = [a.name for a in node.names] if isinstance(node, ast.Import) else (
                    [node.module] if isinstance(node, ast.ImportFrom) and node.module else [])
                for imp in names:
                    last = imp.split('.')[-1]
                    for other in packages:
                        if other != name and last != '__init__' and last in local[other]:
                            fails.append(f'{m["path"]}/{fn}.py imports {imp}, reaching past {other}\'s package '
                                         f'entry (__init__.py) directly into {other}/{last}.py')
    # 5c. import contract, package entry point, LEGACY code included:
    #     #5b above only ever scans files INSIDE registered modules. Typically only a few modules are
    #     registered and most real importers of them are legacy code outside those modules, so #5b
    #     alone would never fire in that shape.
    #     This scans every .py file in the repo (legacy included)
    #     for four import shapes that reach past a registered package's entry point:
    #       1. `from <dotted>.<file> import X`        (a plain from-import of an internal file)
    #       2. `import <dotted>.<file>`                (an absolute import of an internal file)
    #       3. the same as 1/2, but inside a function body (ast.walk, not tree.body, already covers this)
    #       4. `from <dotted> import <file>`           (naming an internal file as the imported symbol)
    #     A registered module's OWN files are excluded (internal cross-file imports are normal), matching
    #     5b's self-exclusion.
    dotted_by_module = {}
    for name, m in mods.items():
        if name not in packages:
            continue  # a flat (non-package) module has no entry point to bypass -- nothing to derive
        dotted, err = dotted_import_name(root, m['path'])
        if err:
            fails.append(err)
            continue
        dotted_by_module[name] = dotted
    own_files = {os.path.join(root, m['path'], fn + '.py') for n, m in mods.items() for fn in local.get(n, ())}
    for path in _iter_repo_py_files(root):
        if path in own_files:
            continue
        try:
            tree = ast.parse(open(path).read())
        except (SyntaxError, UnicodeDecodeError):
            continue
        rel = os.path.relpath(path, root)
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    for oname, dotted in dotted_by_module.items():
                        prefix = dotted + '.'
                        if alias.name.startswith(prefix) and alias.name[len(prefix):] in local[oname] - {'__init__'}:
                            fails.append(f'{rel} imports {alias.name}, reaching past {oname}\'s package entry '
                                         f'(__init__.py) directly into {oname}/{alias.name[len(prefix):]}.py')
            elif isinstance(node, ast.ImportFrom):
                if node.level == 0:
                    resolved = node.module
                else:
                    # Relative-import handling, ported from the upstream checker (Python piece only).
                    # Note: a
                    # RELATIVE import (`from .x import y` / `from ..x import y`) was
                    # invisible here -- the check above only ever compared an ABSOLUTE
                    # dotted node.module. Resolve it against the IMPORTING FILE's own
                    # enclosing package first, the same way Python itself resolves it
                    # (importlib.util.resolve_name), then feed the result into the SAME
                    # prefix/exact match below -- once resolved, a relative bypass is
                    # indistinguishable from an absolute one. An importer with no
                    # enclosing __init__.py, or a level that runs out of package
                    # components, is a named, loud FAIL here -- never a skip or crash
                    # (the same rule already governing dotted_import_name's own
                    # ancestor-gap case).
                    importer_rel_dir = os.path.relpath(os.path.dirname(path), root)
                    importer_pkg, ierr = dotted_import_name(root, importer_rel_dir)
                    if ierr:
                        fails.append(f'{rel}:{node.lineno}: relative import cannot be resolved -- {ierr}')
                        continue
                    rel_name = '.' * node.level + (node.module or '')
                    try:
                        resolved = importlib.util.resolve_name(rel_name, importer_pkg)
                    except ImportError as e:
                        fails.append(f'{rel}:{node.lineno}: relative import "from {rel_name} import ..." '
                                     f'could not be resolved -- {e}')
                        continue
                if resolved is None:
                    continue
                for oname, dotted in dotted_by_module.items():
                    prefix = dotted + '.'
                    if resolved.startswith(prefix) and resolved[len(prefix):] in local[oname] - {'__init__'}:
                        fails.append(f'{rel} imports {resolved}, reaching past {oname}\'s package entry '
                                     f'(__init__.py) directly into {oname}/{resolved[len(prefix):]}.py')
                    elif resolved == dotted:
                        for alias in node.names:
                            if alias.name in local[oname] - {'__init__'}:
                                fails.append(f'{rel} does `from {resolved} import {alias.name}`, reaching past '
                                             f'{oname}\'s package entry (__init__.py) directly into '
                                             f'{oname}/{alias.name}.py')
    # 6. generated files are fresh
    gen = {'MODULE_MAP.md': _module_map(reg), os.path.join('.sop', 'function_index.json'): _function_index(root, reg)}
    for rel, want in gen.items():
        path = os.path.join(root, rel)
        if write:
            os.makedirs(os.path.dirname(path) or root, exist_ok=True)
            open(path, 'w').write(want)
        elif not os.path.isfile(path) or open(path).read() != want:
            fails.append(f'{rel} is stale or missing (run tools/sop_check.py --write)')
    return fails, warns


if __name__ == '__main__':
    args = [a for a in sys.argv[1:] if a != '--write']
    repo = args[0] if args else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    f, w = check(repo, write='--write' in sys.argv)
    for x in w:
        print('WARN', x)
    for x in f:
        print('FAIL', x)
    print('RESULT', 'PASS' if not f else f'FAIL ({len(f)})')
    sys.exit(1 if f else 0)
